import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ShoppingList from "@/components/ShoppingList";
import Cards from "@/components/Cards";
import ButtonTest from "@/components/ButtonTest";
import Input from "@/components/input";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>Learning React</p>
          <div>Tutorial 1</div>
        </div>
        <div>
          <p>Component1: </p>
          <Input />
          <ButtonTest />
          <Cards />
          <ShoppingList />
        </div>
      </main>
    </>
  );
}
